### PR TITLE
Bumped cake version to 0.30.0.

### PR DESCRIPTION
**Pull request by jzeferino**
Fixed part of #15.

### CODE REVIEW

**Comment by jzeferino** [comment]
My changes didn't change any `Execute` flag. I don't understand.

**Comment by ecampidoglio** [comment]
If you look at your commit patch 6921047, you'll see that both `Cake.Curl.csproj` and `Cake.Curl.Tests.csproj` have the following modification:

    100755 → 100644

This means that those files used to have the `Execute` flag (`100755`) but now they're treated as regular files (`100644`). You have likekly not done intentionally, but your IDE or your Git client might have removed the `Execute` flag on your behalf.

That change is correct, I just made it into a separate commit, namely 1835625.

**Comment by jzeferino** [comment]
Bump.

**Comment by jzeferino** [comment]
Should I apply this on top of your commit?

**Comment by ecampidoglio** [comment]
@jzeferino Yes ­– you can just rebase your PR branch on top of `master`.

**Pull request closed without merging**
